spring.application.name=Cadence

spring.datasource.url=jdbc:postgresql://localhost:5432/cadence
spring.datasource.username=cadence
spring.datasource.password=cadence

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=Q9vX#7LmP2@zNf8!Rw4Kd$Yh1Tc&Jm6UsE3BgWp^
app.jwt.expiration-ms=86400000